In [1]:
from google.colab import files

uploaded = files.upload()

Saving inventory DA.csv to inventory DA.csv
Saving order_items DA.csv to order_items DA.csv
Saving orders DA.csv to orders DA.csv
Saving payments DA.csv to payments DA.csv
Saving products DA.csv to products DA.csv
Saving returns DA.csv to returns DA.csv
Saving suppliers DA.csv to suppliers DA.csv
Saving customers DA.csv to customers DA.csv

Load all files

In [3]:
import pandas as pd

customers = pd.read_csv("customers DA.csv")
orders = pd.read_csv("orders DA.csv")
order_items = pd.read_csv("order_items DA.csv")
payments = pd.read_csv("payments DA.csv")
products = pd.read_csv("products DA.csv")
returns = pd.read_csv("returns DA.csv")
suppliers = pd.read_csv("suppliers DA.csv")
inventory = pd.read_csv("inventory DA.csv")

In [4]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Payments:", payments.shape)
print("Products:", products.shape)
print("Returns:", returns.shape)
print("Suppliers:", suppliers.shape)
print("Inventory:", inventory.shape)

Customers: (10000, 17)
Orders: (50000, 19)
Order Items: (100000, 11)
Payments: (50000, 13)
Products: (1000, 17)
Returns: (10000, 10)
Suppliers: (200, 14)
Inventory: (1000, 11)

import library

In [5]:
import pandas as pd

In [6]:
import os

os.listdir()

['.config',
 'customers DA.csv',
 'products DA.csv',
 'payments DA.csv',
 'order_items DA.csv',
 'orders DA.csv',
 'returns DA.csv',
 'suppliers DA.csv',
 'inventory DA.csv',
 'sample_data']

Customers Data cleaning

In [7]:
customers.head()

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
0,CUST00001,Kunal,Gupta,kunal.gupta223@gmail.com,9117912889,Guwahati,Assam,314040,Male,54,New,30-07-2024,10-04-2025,0,1,7,1028341.51
1,CUST00002,Aryan,Gupta,aryan.gupta336@yahoo.in,9271550550,Navi Mumbai,Maharashtra,799535,Female,26,Budget,05-07-2023,03-05-2024,1,1,1,20337.39
2,CUST00003,Akash,Chatterjee,akash.chatterjee584@hotmail.com,9559676548,Surat,Gujarat,738196,Female,24,Regular,14-05-2022,31-10-2023,1,1,7,265688.26
3,CUST00004,Madhuri,Walia,madhuri.walia878@gmail.com,9673322422,Gwalior,Madhya Pradesh,238106,Female,23,Regular,21-01-2025,22-05-2025,1,0,7,173446.94
4,CUST00005,Vishal,Das,vishal.das342@yahoo.in,9920855521,Dhanbad,Jharkhand,783291,Female,59,Regular,06-06-2023,29-03-2024,1,0,4,239808.60

In [8]:
customers.shape

(10000, 17)

In [9]:
customers.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'phone', 'city',
       'state', 'pincode', 'gender', 'age', 'segment', 'registration_date',
       'last_login_date', 'is_verified', 'is_active', 'total_orders',
       'total_spent'],
      dtype='object')

In [10]:
customers.dtypes

customer_id           object
first_name            object
last_name             object
email                 object
phone                  int64
city                  object
state                 object
pincode                int64
gender                object
age                    int64
segment               object
registration_date     object
last_login_date       object
is_verified            int64
is_active              int64
total_orders           int64
total_spent          float64
dtype: object

In [11]:
customers.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                0
phone                0
city                 0
state                0
pincode              0
gender               0
age                  0
segment              0
registration_date    0
last_login_date      0
is_verified          0
is_active            0
total_orders         0
total_spent          0
dtype: int64

In [12]:
customers.isnull().mean().mul(100).round(2)

customer_id          0.0
first_name           0.0
last_name            0.0
email                0.0
phone                0.0
city                 0.0
state                0.0
pincode              0.0
gender               0.0
age                  0.0
segment              0.0
registration_date    0.0
last_login_date      0.0
is_verified          0.0
is_active            0.0
total_orders         0.0
total_spent          0.0
dtype: float64

In [13]:
customers.duplicated().sum()

np.int64(0)

In [14]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [15]:
(customers["total_orders"] == 0).sum()

np.int64(457)

In [16]:
customers["is_verified"].value_counts()

is_verified
1    8418
0    1582
Name: count, dtype: int64

In [18]:
customers["is_active"].value_counts()

is_active
1    8755
0    1245
Name: count, dtype: int64

In [19]:
customers["age"].describe()

count    10000.00000
mean        41.67630
std         13.83438
min         18.00000
25%         30.00000
50%         42.00000
75%         54.00000
max         65.00000
Name: age, dtype: float64

In [20]:
customers["total_orders"].describe()

count    10000.000000
mean         5.000000
std          3.069942
min          0.000000
25%          3.000000
50%          5.000000
75%          7.000000
max         19.000000
Name: total_orders, dtype: float64

In [21]:
customers["total_spent"].describe()

count    1.000000e+04
mean     3.147386e+05
std      2.903266e+05
min      0.000000e+00
25%      8.842337e+04
50%      2.356611e+05
75%      4.660584e+05
max      1.999913e+06
Name: total_spent, dtype: float64

In [22]:
customers["gender"].value_counts(dropna=False)

gender
Male      5168
Female    4564
Other      268
Name: count, dtype: int64

In [23]:
customers["segment"].value_counts(dropna=False)

segment
Regular     4026
Budget      2505
Premium     1501
New         1488
Inactive     480
Name: count, dtype: int64

In [24]:
customers["registration_date"].head(10)

0    30-07-2024
1    05-07-2023
2    14-05-2022
3    21-01-2025
4    06-06-2023
5    06-04-2022
6    10-06-2022
7    04-08-2021
8    24-11-2022
9    20-11-2024
Name: registration_date, dtype: object

Convert registration_date to datetime

In [25]:
customers["registration_date"] = pd.to_datetime(
    customers["registration_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [26]:
customers["registration_date"].dtype

dtype('<M8[ns]')

In [27]:
customers["registration_date"].isnull().sum()

np.int64(0)

In [28]:
customers["last_login_date"].head(10)

0    10-04-2025
1    03-05-2024
2    31-10-2023
3    22-05-2025
4    29-03-2024
5    21-10-2022
6    06-04-2023
7    29-03-2023
8    18-05-2025
9    21-01-2025
Name: last_login_date, dtype: object

Convert last_login_date to datetime

In [29]:
customers["last_login_date"] = pd.to_datetime(
    customers["last_login_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [30]:
customers["last_login_date"].dtype

dtype('<M8[ns]')

In [31]:
customers["last_login_date"].isnull().sum()

np.int64(0)

In [32]:
customers["phone"].head(10)

0    9117912889
1    9271550550
2    9559676548
3    9673322422
4    9920855521
5    9809180864
6    9718044438
7    9143287667
8    9238159208
9    9938859478
Name: phone, dtype: int64

In [33]:
customers["phone"].astype(str).str.len().value_counts()

phone
10    10000
Name: count, dtype: int64

In [34]:
customers["pincode"].astype(str).str.len().value_counts()

pincode
6    10000
Name: count, dtype: int64

In [35]:
email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

customers["email"].str.match(email_pattern).value_counts()

email
True    10000
Name: count, dtype: int64

Validate total_spent

In [36]:
customers["total_spent"].lt(0).sum()

np.int64(0)

In [37]:
customers["total_spent"].nlargest(10)

3450    1999913.04
5551    1997346.16
6800    1983951.26
7345    1928170.04
5534    1918090.04
26      1893655.96
7424    1892535.76
7573    1863718.85
1061    1858684.83
4362    1857479.68
Name: total_spent, dtype: float64

In [38]:
customers[
    (customers["total_orders"] == 0) &
    (customers["total_spent"] > 0)
].shape

(0, 17)

In [39]:
customers[
    (customers["total_orders"] > 0) &
    (customers["total_spent"] == 0)
].shape

(0, 17)

In [40]:
customers.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                0
phone                0
city                 0
state                0
pincode              0
gender               0
age                  0
segment              0
registration_date    0
last_login_date      0
is_verified          0
is_active            0
total_orders         0
total_spent          0
dtype: int64

In [41]:
customers.to_csv("customers_cleaned.csv", index=False)

In [42]:
import os

os.path.exists("customers_cleaned.csv")

True